[build-system]
requires = ["hatchling<=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "soman"
version = "2024.0.0"
dependencies = [
    "networkx==3.3",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "rdkit==2024.3.1",
    "tqdm==4.66.4",
]
requires-python = ">=3.11"
authors = [
  {name = "Roxane Jacob", email = "roxane.axel.jacob@univie.ac.at"},
]
maintainers = [
  {name = "Roxane Jacob", email = "roxane.axel.jacob@univie.ac.at"}
]
description = "Annotates the Sites of Metabolism (SoMs) of substrate-metabolite pairs."
readme = "README.md"
license = {text = "MIT License"}

[project.optional-dependencies]
visualize = ["ipykernel", 'ipywidgets']
